"""add pinned archived starred and search index

Revision ID: 918299d3f6a7
Revises: 3290c98631ec
Create Date: 2026-04-27 13:30:06.706382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918299d3f6a7'
down_revision: Union[str, None] = '3290c98631ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starred_messages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('starred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.add_column('chat_participants', sa.Column('pinned', sa.Boolean(), nullable=True))
    op.add_column('chat_participants', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'archived')
    op.drop_column('chat_participants', 'pinned')
    op.drop_table('starred_messages')
    # ### end Alembic commands ###
