"""add group features and message deliveries

Revision ID: e83b64f73c86
Revises: d34910fbe6c1
Create Date: 2026-04-27 12:02:23.632083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83b64f73c86'
down_revision: Union[str, None] = 'd34910fbe6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_deliveries',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='deliverystatus'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.add_column('chat_participants', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('chat_participants', sa.Column('muted_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'muted_until')
    op.drop_column('chat_participants', 'role')
    op.drop_table('message_deliveries')
    # ### end Alembic commands ###
